package admin

/*
# What would the admin want?
# The admin should be able to:
* Create an instance of every schema (except autogenerated)
* Delete an instance of every schema (except autogenerated)
*/
